//! Plugin installation and default directory discovery.
//!
//! Locates the platform-specific plugin directory, writes out the bundled
//! binary plugins embedded at compile time via atomic file replacement, and
//! installs syntax definitions into `{plugin_dir}/syntaxes/`.
//!
//! Bundled binary plugins (`iconize`, `markdown`, `python`, `rust`, `go`,
//! `json`, `sh`, `yaml`, `terraform`) are embedded at compile time via
//! `build.rs` →
//! `$OUT_DIR/plugin_binaries.rs` — no search-path dance or fallback `cargo
//! build` at runtime. This ensures they are always available for non-source
//! installs (release artifacts, Homebrew, etc.).
//!
//! Bundled syntax plugins (`toml`, `typescript`, `dockerfile`,
//! `nginx`, `justfile`) are embedded via `include_str!` and written to the
//! `syntaxes/` subdirectory on first run. The matching
//! `terraform.sublime-syntax` ships the same way, but it declares its own
//! `file_extensions` (`.tf`, `.tfvars`, `.hcl`) and is auto-discovered from
//! `{plugin_dir}/syntaxes/` rather than being managed by a `[plugins]`
//! entry — the `terraform` plugin itself is a process plugin (language
//! provider, `fold` capability).

include!(concat!(env!("OUT_DIR"), "/plugin_binaries.rs"));

use std::path::{Path, PathBuf};

use crate::plugin::types::{PluginEntry, PluginKind};

/// Returns `(name, PluginEntry)` pairs for every plugin that ships with `mantis`.
///
/// All plugins shipped with `mantis` (markdown, iconize, python, rust, go, json, sh,
/// yaml, k8s, terraform, toml, typescript, dockerfile, nginx, justfile) are enabled by
/// default. User config
/// entries with `or_insert` always win over these defaults, so an explicit
/// `enabled = false` in `mantis.toml` is respected.
pub(crate) fn bundled_plugin_entries() -> Vec<(String, PluginEntry)> {
    let mut entries = Vec::new();
    for (name, binary_name, _data) in BUNDLED_PLUGINS {
        let filename = if cfg!(windows) {
            format!("{binary_name}.exe")
        } else {
            binary_name.to_string()
        };
        // Store the path relative to `default_plugin_dir()` (resolved at spawn
        // time in `PluginManager::activate_all`). An absolute path here would be
        // serialised verbatim into the user's `mantis.toml` on the first plugin
        // toggle, pinning a machine-specific home directory into a config that is
        // meant to be portable.
        let enabled = true;
        entries.push((
            name.to_string(),
            PluginEntry {
                path: PathBuf::from(filename),
                enabled,
                kind: PluginKind::Process,
                extensions: Vec::new(),
                syntax_file: None,
                events: Vec::new(),
            },
        ));
    }
    for (name, syntax_rel_path, extensions) in BUNDLED_SYNTAX_PLUGIN_ENTRIES {
        let extensions: Vec<String> = extensions.iter().map(|s| s.to_string()).collect();
        entries.push((
            name.to_string(),
            PluginEntry {
                path: PathBuf::from(syntax_rel_path),
                enabled: true,
                kind: PluginKind::Syntax,
                extensions,
                syntax_file: Some(PathBuf::from(syntax_rel_path)),
                events: Vec::new(),
            },
        ));
    }
    entries
}

/// Default plugin discovery directory.
///
/// - Linux/macOS: `$XDG_CONFIG_HOME/mantis/plugins/` (falls back to
///   `~/.config/mantis/plugins/` when the variable is unset)
/// - Windows:     `%APPDATA%\mantis\plugins\`
pub(crate) fn default_plugin_dir() -> PathBuf {
    dirs_next().unwrap_or_else(|| PathBuf::from("."))
}

fn dirs_next() -> Option<PathBuf> {
    #[cfg(windows)]
    {
        std::env::var_os("APPDATA").map(|p| PathBuf::from(p).join("mantis").join("plugins"))
    }
    #[cfg(not(windows))]
    {
        std::env::var_os("XDG_CONFIG_HOME")
            .map(PathBuf::from)
            .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config")))
            .map(|base| base.join("mantis").join("plugins"))
    }
}

/// List of (user-facing_name, binary_name, embedded_binary_data) for each
/// bundled process plugin. The byte data is generated by `build.rs` and
/// injected via `include!` at the top of this file, so the binaries are
/// always available regardless of install method.
pub(crate) const BUNDLED_PLUGINS: &[(&str, &str, &[u8])] = &[
    ("iconize", "iconize", ICONIZE),
    ("markdown", "markdown", MARKDOWN),
    ("python", "python", PYTHON),
    ("rust", "rust", RUST),
    ("go", "go", GO),
    ("json", "json", JSON),
    ("sh", "sh", SH),
    ("yaml", "yaml", YAML),
    ("k8s", "k8s", K8S),
    ("terraform", "terraform", TERRAFORM),
];

/// Filenames of old shell-script plugins superseded by the current Rust binaries.
///
/// These were shipped by mantis up to 0.7.x and lived in the plugin directory
/// as standalone shell scripts. They are no longer needed and are silently
/// removed on startup so stale files cannot be accidentally re-enabled.
pub(crate) const RETIRED_BUNDLED_PLUGINS: &[&str] = &[
    "git-diff.sh",
    "git-log.sh",
    "iconize.sh",
    "mantis-plugin-iconize",
    "mantis-plugin-iconize.exe",
    "mantis-plugin-markdown",
    "mantis-plugin-markdown.exe",
];

/// List of (filename, content) for each bundled syntax definition.
const BUNDLED_SYNTAX_PLUGINS: &[(&str, &str)] = &[
    (
        "terraform.sublime-syntax",
        include_str!("../../plugins/terraform/syntaxes/terraform.sublime-syntax"),
    ),
    (
        "toml.sublime-syntax",
        include_str!("../../plugins/toml/syntaxes/toml.sublime-syntax"),
    ),
    (
        "typescript.sublime-syntax",
        include_str!("../../plugins/typescript/syntaxes/typescript.sublime-syntax"),
    ),
    (
        "dockerfile.sublime-syntax",
        include_str!("../../plugins/dockerfile/syntaxes/dockerfile.sublime-syntax"),
    ),
    (
        "nginx.sublime-syntax",
        include_str!("../../plugins/nginx/syntaxes/nginx.sublime-syntax"),
    ),
    (
        "justfile.sublime-syntax",
        include_str!("../../plugins/justfile/syntaxes/justfile.sublime-syntax"),
    ),
];

/// List of (name, syntax_rel_path, extensions) for syntax plugin [plugins] entries.
/// Seeded into the config so syntax plugins appear in the plugin palette.
///
/// `terraform` is deliberately absent: its `.sublime-syntax` is still installed
/// (see `BUNDLED_SYNTAX_PLUGINS`) but is auto-discovered from `{plugin_dir}/syntaxes/`
/// rather than managed by a config entry, and the `terraform` plugin itself is a
/// process language provider (fold capability) registered in `BUNDLED_PLUGINS`.
const BUNDLED_SYNTAX_PLUGIN_ENTRIES: &[(&str, &str, &[&str])] = &[
    ("toml", "syntaxes/toml.sublime-syntax", &["toml"]),
    (
        "typescript",
        "syntaxes/typescript.sublime-syntax",
        &["ts", "tsx", "mts", "cts", "jsx"],
    ),
    (
        "dockerfile",
        "syntaxes/dockerfile.sublime-syntax",
        &["dockerfile"],
    ),
    ("nginx", "syntaxes/nginx.sublime-syntax", &[]),
    ("justfile", "syntaxes/justfile.sublime-syntax", &[]),
];

/// Copies every bundled plugin to the plugin directory if it doesn't already
/// exist there, or overwrites it if the installed binary differs from the
/// embedded one (e.g. after a mantis upgrade). Syntax definitions go into
/// `{plugin_dir}/syntaxes/`. Also removes any retired shell-script plugins
/// that were superseded by Rust binaries (pre-0.8 upgrade cleanup).
pub(crate) fn install_bundled_plugins() {
    let dir = default_plugin_dir();
    let _ = std::fs::create_dir_all(&dir);

    for (_name, binary_name, data) in BUNDLED_PLUGINS {
        let binary_filename = if cfg!(windows) {
            format!("{binary_name}.exe")
        } else {
            binary_name.to_string()
        };
        let plugin_path = dir.join(&binary_filename);
        if data.is_empty() {
            continue;
        }
        // Bundled plugin names are known ahead of time, so an exact-name
        // match here is treated as one of our own binaries and overwritten
        // on content mismatch, even if a user placed their own file there.
        let up_to_date = std::fs::read(&plugin_path)
            .map(|existing| existing == *data)
            .unwrap_or(false);
        if up_to_date {
            set_executable(&plugin_path);
            continue;
        }
        write_binary_atomically(&dir, &plugin_path, &binary_filename, data);
    }

    let syntax_dir = dir.join("syntaxes");
    let _ = std::fs::create_dir_all(&syntax_dir);
    for (name, content) in BUNDLED_SYNTAX_PLUGINS {
        let path = syntax_dir.join(name);
        let up_to_date = std::fs::read_to_string(&path)
            .map(|existing| existing == *content)
            .unwrap_or(false);
        if !up_to_date {
            write_file_atomically(&syntax_dir, &path, name, content.as_bytes());
        }
    }

    remove_retired_bundled_plugins();
}

fn write_binary_atomically(dir: &Path, plugin_path: &Path, filename: &str, data: &[u8]) {
    let tmp_path = dir.join(format!(".{filename}.tmp.{}", std::process::id()));
    if std::fs::write(&tmp_path, data).is_ok() {
        set_executable(&tmp_path);
        if std::fs::rename(&tmp_path, plugin_path).is_err() {
            let _ = std::fs::remove_file(plugin_path);
            if std::fs::rename(&tmp_path, plugin_path).is_err()
                && std::fs::write(plugin_path, data).is_ok()
            {
                set_executable(plugin_path);
            }
        }
        let _ = std::fs::remove_file(&tmp_path);
    }
}

fn write_file_atomically(dir: &Path, file_path: &Path, filename: &str, data: &[u8]) {
    let tmp_path = dir.join(format!(".{filename}.tmp.{}", std::process::id()));
    if std::fs::write(&tmp_path, data).is_ok() {
        if std::fs::rename(&tmp_path, file_path).is_err() {
            let _ = std::fs::remove_file(file_path);
            let _ = std::fs::rename(&tmp_path, file_path);
        }
        let _ = std::fs::remove_file(&tmp_path);
    }
}

/// Removes retired bundled plugin files from the plugin directory.
///
/// Deletes only exact-name matches that mantis is known to have shipped
/// (see `RETIRED_BUNDLED_PLUGINS`). User-authored plugins are never touched.
/// Errors are silently ignored so a permissions issue does not crash startup.
pub(crate) fn remove_retired_bundled_plugins() {
    let dir = default_plugin_dir();
    for name in RETIRED_BUNDLED_PLUGINS {
        let path = dir.join(name);
        if path.exists() {
            let _ = std::fs::remove_file(&path);
        }
    }
}

/// Returns the list of retired plugin filenames that should be removed
/// from the plugin directory and filtered out of config `[plugins]` entries.
pub(crate) fn retired_bundled_plugins() -> &'static [&'static str] {
    RETIRED_BUNDLED_PLUGINS
}

#[cfg(unix)]
fn set_executable(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755));
}
#[cfg(not(unix))]
fn set_executable(_path: &Path) {}
